README.md
=> [Test] feature to dev pr test

README.md
=> [Test] feature to dev

README.md
User story 완성
[Test] dev to test
=> [Test] dev to test

README.md
[Test] feature/test3 before completing test
=> [Test] feature/test3 before completing test

README.md
=> [Test] test 완료

README.md
=> [Test] test 완료 

README.md
=> sycn dev with product

.gitignore, backend/pom.xml, backend/src/main/java/com/example/backswim/pool/controller/PoolController.java, backend/src/main/java/com/example/backswim/pool/error/PoolError.java, backend/src/main/resources/logback.xml, backend/src/test/java/com/example/backswim/PoolTest.java
Jira Number : BAC-37
Description :
파라미터 타입 오류시 내부 정보 유출 관련 수정
테스트 코드 추가
Unit test:
GetPoolMapForLocate API Success ParameterNull , ParameterTypeError Unit test
=> Title : [Back] 지도표시 수영장 데이터 API 에러 처리 및 TestCode

backend/pom.xml, backend/src/main/java/com/example/backswim/pool/controller/PoolController.java, backend/src/main/java/com/example/backswim/pool/controller/PoolDetailController.java, backend/src/main/java/com/example/backswim/pool/entity/PoolDetailEntity.java, backend/src/main/java/com/example/backswim/pool/excetption/poolexception/PoolNotFoundException.java, backend/src/main/java/com/example/backswim/pool/model/dto/PoolDetailInfoDto.java, backend/src/main/java/com/example/backswim/pool/params/GetPoolDetailParam.java, backend/src/main/java/com/example/backswim/pool/repository/PoolDetailRepostiory.java, backend/src/main/java/com/example/backswim/pool/service/PoolDetailService.java, backend/src/main/java/com/example/backswim/pool/service/PoolDetailServiceImpl.java, backend/src/test/java/com/example/backswim/PoolDetailTest.java
http://host/api/pooldetail/getpolldetail
content-type : application-json
parameter : {id  : Integer}
GetPoolDetailSuccess (API가 성공적으로 테스트를 마쳤을때)
TestTime 150ms 
GetPoolDetailNoParameterFail(API 요청시 파라미터 값 null)
5~10ms 
id : null  
GetPoolDetailWrongParameterFail(파라미터 값에 Integer가 아닌 값이 들어갔을경우)
8ms
id : 1a 
GetPollDetailNotFoundParameterFail(요청 파라미터에 대해 수영장 상세정보 검색 실패)
runtime : 12ms
id : 1 (id 1인데이터는 없습니다. )
=> [BAC-38][Back][Pool] 수영장 상세정보 API

frontend/src/components/home/home.css, frontend/src/components/home/home.js, frontend/src/components/pool/pool.css, frontend/src/components/pool/pool.js, frontend/src/components/sideBar/sideBar.css, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBar.test.js
Jira Number: BAC-31
Description:
검색(엔진), 검색(지역), 즐겨찾기 로 연결되는 side bar 컴포넌트 입니다.
- UI 컴포넌트 (O)
- 서서히 열리는 애내메이션(추후 버튼 handler 등록 후)
Unit test:
- snap shot
PASS src/components/sideBar/sideBar.test.js
[Pool] BAC-31 SideBar 컴포넌트
✓ SnapShot test (33 ms)
=> [BAC-31]: [Front][Pool] side bar 컴포넌트

backend/src/main/java/com/example/backswim/configuration/SecurityConfiguration.java, backend/src/main/java/com/example/backswim/pool/apiresult/APIResult.java, backend/src/main/java/com/example/backswim/pool/apiresult/CommonAPI.java, backend/src/main/java/com/example/backswim/pool/apiresult/PoolAPI.java, backend/src/main/java/com/example/backswim/pool/apiresult/PoolDetailAPI.java, backend/src/main/java/com/example/backswim/pool/controller/PoolController.java, backend/src/main/java/com/example/backswim/pool/controller/PoolDetailController.java, backend/src/main/java/com/example/backswim/pool/dto/PoolDetailDto.java, backend/src/main/java/com/example/backswim/pool/dto/PoolDto.java, backend/src/main/java/com/example/backswim/pool/entity/PoolDetailEntity.java, backend/src/main/java/com/example/backswim/pool/entity/PoolEntity.java, backend/src/main/java/com/example/backswim/pool/params/repository/PoolDetailRepostiory.java, backend/src/main/java/com/example/backswim/pool/params/repository/PoolRepository.java, backend/src/main/java/com/example/backswim/pool/service/PoolDetailService.java, backend/src/main/java/com/example/backswim/pool/service/PoolDetailServiceImpl.java, backend/src/main/java/com/example/backswim/pool/service/PoolService.java, backend/src/main/java/com/example/backswim/pool/service/PoolServiceImpl.java
* getpoolmapforlocate response 양식변경
* getpooldetail response 양식변경
=> [BAC-38][Back][Pool] 수영장 상세정보 API & [BAC-37] 수영장 지도 검색 API

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/common/myRequest.js, frontend/src/components/pool/pool.js, frontend/webpack.config.js
- 로그인, 비로그인  확인(추후)
- 필요한 데이터 캐시 (수영장 정보)(추후)
- 자동 로그인 기능(추후)
- 지도 표시 API(O)
- 현재 위치 정보를 허용(O)
- 해당 지도에 속해있는 지도 표시(O)
- webpack 설정(O)
X
=> [BAC-43]: [Front][Pool] 홈페이지 컴포넌트

.gitignore, frontend/public/index.html, frontend/src/common/myRequest.js, frontend/src/components/header/header.css, frontend/src/components/home/home.css, frontend/src/components/home/home.js, frontend/src/components/sideBar/backButton.css, frontend/src/components/sideBar/backButton.js, frontend/src/components/sideBar/sideBar.css, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBarFavorite.js, frontend/src/components/sideBar/sideBarLocation.js, frontend/src/components/sideBar/sideBarText.css, frontend/src/components/sideBar/sideBarText.js, frontend/src/root.css, frontend/src/utils/debounce.js
Jira Number:  BAC-33
Description:
- UI 컴포넌트 (O)
- 애니메이션 (0)
- css border 수정(O)
- 뒤로가기 버튼(O)
Unit test:
X
TODO:
- 뒤로가기 버튼 esc 연동
- 수영장 추천 리스트 keyup 이벤트 등록
=> [BAC-33]: [Front][Pool] 사이드바 컴포넌트 내 검색(지역) 컴포넌트

frontend/src/common/myNodes.js, frontend/src/common/myRequest.js, frontend/src/common/myTypes.js, frontend/src/components/home/home.js, frontend/src/components/pool/pool.js, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBarDetail.css, frontend/src/components/sideBar/sideBarDetail.js, frontend/src/components/sideBar/sideBarDetailItem.css, frontend/src/components/sideBar/sideBarDetailItem.js, frontend/src/components/sideBar/sideBarText.css, frontend/src/root.css, frontend/src/utils/myTime.js
- UI 컴포넌트 (O)
- 애니메이션 (개선 필요)
- 지도 이동 가능 (O)
- 마커 이벤트 핸들러(O)
X
Q) 컴포넌트가 가지고 있는 역할의 범위
Q) sibling끼리의 state 교환 (불필요한 렌더링 발생)
Q) paramter 타입 에러
Q) server request 에러 처리
=> [BAC-34]: [Front][Pool] 수영장 상세 컴포넌트

frontend/src/common/myNodes.js, frontend/src/common/myRequest.js, frontend/src/common/myTypes.js, frontend/src/components/pool/pool.js, frontend/src/components/sideBar/sideBar.css, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBarDetail.css, frontend/src/components/sideBar/sideBarDetail.js, frontend/src/components/sideBar/sideBarDetailItem.js, frontend/src/components/sideBar/sideBarLocation.css, frontend/src/components/sideBar/sideBarLocation.js, frontend/src/root.css
Jira Number:  BAC-23
Description:
- UI 컴포넌트 (O)
- 애니메이션 (개선 필요)
Unit test:
X
Q) refactoring 필요
=> [BAC-23]: [Front][Pool] 수영장 상세 컴포넌트

frontend/src/App.js, frontend/src/components/home/home.js, frontend/src/components/pool/pool.js, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBarDetailItem.js, frontend/src/components/sideBar/sideBarLocation.js, frontend/src/components/sideBar/sideBarText.js, frontend/webpack.config.js
=> [BAC-23] [Front] 프론트엔드 초기설정

frontend/.prettierrc.json, frontend/src/common/myNodes.js, frontend/src/common/myTypes.js, frontend/src/components/home/home.js, frontend/src/components/pool/pool.js, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBarText.js, frontend/src/root.css
- prettier 설정 수정
- 검색 엔진 방향키(위,아래) 핸들러 추가 (검색 결과 탐색)
- 검색 엔진 엔터 핸들러 추가 (검색 결과 선택)
- 검색 엔진 클릭 핸들러 추가 (검색 결과 선택)
X
rendering이 필요 이상 되는 것 Vs state를 누가 가지고 있나?
=> [BAC-33]: [Front][Pool] 사이드바 컴포넌트 내 검색 컴포넌트

frontend/webpack.config.js
=> [BAC-29]: [Front][Pool] header 컴포넌트

frontend/jest.config.js, frontend/jsconfig.json, frontend/src/App.js, frontend/src/components/home/home.js, frontend/src/components/pool/pool.js, frontend/src/components/sideBar/sideBar.js, frontend/src/components/sideBar/sideBarDetailItem.js, frontend/src/components/sideBar/sideBarLocation.js, frontend/src/components/sideBar/sideBarText.js, frontend/webpack.config.js
- webpack alias 설정
- jest alias 적용
- vscode alias 설정
X
설정 블로그 정리
=> [BAC-23]: [Front] 프론트엔드 초기설정

backend/pom.xml, backend/src/main/java/com/example/backswim/common/api/enums/StatusEnum.java, backend/src/main/java/com/example/backswim/component/JwtComponent.java, backend/src/main/java/com/example/backswim/configuration/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backswim/configuration/SecurityConfiguration.java, backend/src/main/java/com/example/backswim/configuration/UserSecurityAdapter.java, backend/src/main/java/com/example/backswim/configuration/WebConfigure.java, backend/src/main/java/com/example/backswim/member/controller/LoginController.java, backend/src/main/java/com/example/backswim/member/entity/UserEntity.java, backend/src/main/java/com/example/backswim/member/exception/MemberNotEmailAuthException.java, backend/src/main/java/com/example/backswim/member/exception/UserNotEmailAuthException.java, backend/src/main/java/com/example/backswim/member/exception/WrongPasswordException.java, backend/src/main/java/com/example/backswim/member/params/login/LoginRequestParam.java, backend/src/main/java/com/example/backswim/member/repository/UserRepository.java, backend/src/main/java/com/example/backswim/member/service/UserDetailServiceImpl.java, backend/src/main/java/com/example/backswim/member/service/UserService.java, backend/src/main/java/com/example/backswim/member/service/UserServiceImpl.java, backend/src/test/java/com/example/backswim/TestPackage.java, backend/src/test/java/com/example/backswim/UserJoinTest.java, backend/src/test/java/com/example/backswim/UserLoginTest.java
[BAC-16] BackEnd 유저 로그인 
* WebConfigure 재설정
* SpringSecurity UserAuthenticate 설정
* JwtToken 발급
* JwtToken을 통한 SpringSecurity UserAuthentication 구현
* refreshToken은 아직 미구현
* Loing Unit Test 작성
-> loginSuccessTest 로그인 성공 테스트케이스 111ms
-> loginFailNotEmailAuth 이메일 인증 안되 로그인 실패 테스트 24ms
-> loginFailWrongPassword 로그인 실패 비밀번호 오류 82ms
-> loginFailNullParam 로그인 실패 파라미터 null 8ms
* StatusEnum & Controller 변경
-> WrongPassword , EmailNot Auth 관련 내용 추가
=> [BAC-16] BackEnd 유저 로그인 

backend/src/main/java/com/example/backswim/member/controller/JoinMemberController.java, backend/src/main/java/com/example/backswim/member/params/UserEmailParam.java, backend/src/main/java/com/example/backswim/member/service/UserService.java, backend/src/main/java/com/example/backswim/member/service/UserServiceImpl.java, backend/src/test/java/com/example/backswim/UserJoinTest.java
* 유저 비밀번호 변경 이메일 링크 API
* 비밀번호 초기화 이메일 재전송 API
* 비밀번호 변경 API
* resetPasswordSuccess 비밀번호 초기화 이메일 전송 2s
* resetPasswordFailUserNotFound 12ms
* resetPasswordFailNullParam 8ms
* changePasswordSuccess 98ms
* changePasswordFailNotValidateUUID 13ms
* changePasswordNullParam 9ms
* changePasswordExpiredDate 22ms
=> [BAC-50][BAC-65][BAC-66] 유저 비밀번호 변경

frontend/src/components/emailAuth/emailAuth.js, frontend/src/components/home/home.js, frontend/src/components/signIn/signIn.js
- 로그인 성공하여 라우팅 시 login 정보 함께 전송
X
=> [User][Front] 로그인 컴포넌트

frontend/src/App.js, frontend/src/common/myError.js, frontend/src/common/myRequest.js, frontend/src/components/changePassword/changePassword.css, frontend/src/components/changePassword/changePassword.js, frontend/src/components/resetPassword/resetPassword.css, frontend/src/components/resetPassword/resetPassword.js, frontend/src/components/signIn/signIn.css, frontend/src/components/signIn/signIn.js
BAC-10, BAC-58
- 비밀번호 찾기 컴포넌트
- 악의적인 무수한 요청에 대한 방어
- 이메일 전송 request
x
=> [User][Front] 비밀번호 찾기 컴포넌트

backend/src/main/java/com/example/backswim/component/JwtComponent.java, backend/src/main/java/com/example/backswim/member/controller/LoginController.java, backend/src/main/java/com/example/backswim/member/service/UserServiceImpl.java, backend/src/test/java/com/example/backswim/UserLoginTest.java
* Token Cookie 저장
* (이메일 인증 유무 -> 비밀번호 확인) => (비밀번호 확인 -> 이메일 인증 유무) 로직 변경
Test
Login Test Cookie 값 유무 테스트
=> [BAC-16] 유저 로그인
